[package]
name = "taker"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"
description = "Option-like taking for everyting with a default value."
license = "MIT"

[dependencies]
